### ISSUE TITLE
Can't find 1-wire sensor 

### ISSUE THREAD

**Issue by Mange131** [Rikkert-RS/VenusOS-TemperatureService#5]
The sensor worked when i install it then after couple of minutes it says, it's not connected. Can i check in someway if the sensor is there?

**Comment by Rikkert-RS** [comment]
Hello Mange131,

If the DS18B20 sensor is no longer detected on the 1Wire bus, the service for this sensor is stopped after 1 to 5 minutes and the connection and status is set to nio.

can you please tell or describe how you connected the sensor?
If you are able to login with SSH Console we can check some files.

mfg Rikkert

**Comment by Mange131** [comment]
i use this sensor with pluggable terminal adapter with build in  4.7 pullup
resistor.

https://www.amazon.se/gp/aw/d/B094FKQ9BS?psc=1&ref=ppx_pop_mob_b_asin_image

 Data to gpio 26, 3,3v and earth.
 I have tested the pullup resistor after, and it's ok

Venus os 3.00-39.
Rpi 3b

I have testet two times, from scratch. Because i have probleme with the rpi
can't find my hdmi screen.  second time it work for 2-3 hour till i install
rpigpiosetup.

I have rpi in my boat. Can test it tomorrow, same time as now?

Mvh/ Magnus

**Comment by Rikkert-RS** [comment]
Hello,

ok i think the issue is with rpigpiosetup. you have to modify the gpio list and exclude the gpio 26.

The reason why I changed the pin is that I installed a can hat for a canbus battery and that unfortunately collides. Pin 4 could also cause problems for other people and other raspberry shields.

If it works then you just have to create a custom GPIO list for RpiGpioSetup that's not difficult.

Link->[https://github.com/kwindrem/RpiGpioSetup]

![grafik](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/96136114/ea3aa47a-2dfa-4414-91bb-9f8bff41fe3f)

here a view from the RpiGpioSetup gpio_list file: were you can comment out the Gpio26:
do that with ssh under /data/RpiGpioSetup/FileSets/gpio_list

![grafik](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/96136114/84176b40-0ce5-435c-b739-6f885a4c0683)
![grafik](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/96136114/eef289e0-8d3d-4b59-91a4-f9700b632c0b)

Maybe in the future i can make the pin configurable, or comment out at installation if RpiGpioSetup ist installed

**Comment by Mange131** [comment]
Ok i test that tomorrow

Thanks

Mvh/ Magnus

Den sön 21 maj 2023 22:02Rikkert-RS ***@***.***> skrev:

**Comment by Rikkert-RS** [comment]
@Mange131 
Did you already have time to test the problem is solved

**Comment by Mange131** [comment]
sorry I haven't checked.  have been busy getting the boat ready.  but i did a fresh install of venus today.  and I will test it tomorrow in the boat.  will not install RpiGpioSetup.  I don't think I need it yet.  just need guimods, shutdown manger and your VenusOS-TemperatureService

**Comment by Mange131** [comment]
only worked briefly again.  max one hour.  tried to uninstall and install temperatureService again but then the sensor did not come up.  have installed guimods, rpidisplaysetup. Shutdown manager

**Comment by Rikkert-RS** [comment]
Hi,

Hmm that is not so good. 
How long is your Sensor cable?

You can try an other Port with this method: 
https://github.com/Rikkert-RS/VenusOS-TemperatureService/issues/6#issuecomment-1587847440

otherwise we must check out the logs

**Comment by Mange131** [comment]
ok, going to the boat later today.  I have 2 sensors of 1 and 3 meters to one pullup 4.7k and then from the pullup I have a one cable of 5 meters to the rpi. slightly thicker cable.  Do i need uninstall something?

**Comment by Rikkert-RS** [comment]
Ok 

if you want to switch the Port you don‘t need to uninstall only connect with ssh and change the config.txt file and restart the rpi. 

But I would test the sensors with a shorter cable length beforehand. The voltage drop at 3.3v on the cable length can be considerable.
If the cable is also not shielded, this can also lead to interference if other cables are nearby.

**Comment by Mange131** [comment]
OK thanks

**Comment by Rikkert-RS** [comment]
Some info for 1 Wire bus wiring

http://pvlng.com/1-Wire_Hub
https://www.analog.com/en/technical-articles/guidelines-for-reliable-long-line-1wire-networks.html
https://www.msxfaq.de/sonst/bastelbude/raspi/raspi-1wire.htm

Good choice is to use Cat 5 or 6 Network cable

**Comment by Mange131** [comment]
works with short cable.  and I use pin 26. but under device it looks like this
![Screenshot_20230628-113939](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/125033170/38baa46e-1851-46ea-8373-39764f2e5f1f)

**Comment by Rikkert-RS** [comment]
Interesting, is the sensor running with the temperature values? 
Which Venus OS version are you using?

**Comment by Mange131** [comment]
What do you mean with temperature values? sry English is not my language 😀
I'm using 3.0

Just in the process of running a cat6 cable for the sensors with longer distances

**Comment by Rikkert-RS** [comment]
No problem, English is not my native language either.

I meant if only the metadata to the sensor is missing or also the sensor value, so the temperature value? 
Possibly it is the version 3. At the moment I have still no device runs on V3.0 to test.

For 
> Just in the process of running a cat6 cable for the sensors with longer distances

You can also reduce the pullup resistor from 4.7kOhms to something less, perhaps 3.3kOhms or 2.2kOhms, since the RPI pin voltage is 3.3V.

**Comment by Mange131** [comment]
now both sensors work with the longer cat6 cable.  we'll see how long 😀 and the id number comes up as well

**Comment by Mange131** [comment]
![Screenshot_20230702-133942](https://github.com/Rikkert-RS/VenusOS-TemperatureService/assets/125033170/5f5d929a-3a89-419b-a9af-afb613745923)

**Comment by Rikkert-RS** [comment]
ok, ;) inform me if it's working properly the next days

**Comment by Mange131** [comment]
Ok i do that.
 thanks a lot for your help

**Comment by Mange131** [comment]
only one works for me now.  I will check the cable connection.  think it's all to do with sensor instability.  if you search online about rpi and 1-wire.  so you get quite a lot of hits on those who have problems.  one solution to having more sensors is to maybe be able to have more pins available.

We can probably close this thread now.  thanks so much for all the help

**Comment by Rikkert-RS** [comment]
You can try to get more stable signal if you use 5V suply voltgage to the Sensor. And also a good Power suply for the Raspberry is important too. 

Here is one Link to do so. http://pvlng.com/1-Wire_Hub

Using multiple pins is not a solution in my opinion

But anyway, I'll close the topic now. Much luck.

Rikkert-RS
